# Generated by Django 3.0.6 on 2020-06-25 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('limit', models.IntegerField(default=200)),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0)),
                ('address', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
